version: '3'

services:
##> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    container_name: systemeiodb
    environment:
      POSTGRES_DB: systemeio
      #You should definitely change the password in production
      POSTGRES_PASSWORD: postgres@
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/main
      DATABASE_URL: postgresql://postgres:postgres@@systemeiodb:5432/systemeio?serverVersion=15&charset=utf8
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      #- /var/lib/postgresql/15/main:/var/lib/postgresql/data:rw
      - ./database:/var/lib/postgresql/data
      - ./database/main:/var/lib/postgresql/data
      - /var/run/postgresql:/var/run/postgresql

  php:
    build:
      context: ./
    container_name: systemeioapp


    environment:
      APP_ENV: dev #prod
      TIMEZONE: Asia/Qyzylorda
    
    depends_on:
      - database

    volumes:
      - ./:/app
    ports:
      - 8000:8000
    # networks:
    #   - systemeio-net